
//ARRAYS ARE VARIABLES WHICH CAN HOLD MORE THAN ONE VALUE.
let a = [1,23,34,56,"not present",null, false]  //NOTE: WE CAN STORE MULTIPLE TYPE OF DATA INTO ONE ARRAY.
console.log(a[6])

//TO MEASURE THE LENGTH OF AN ARRAY WE USE .length PROPERTY
console.log(a.length)

//ARRAYS ARE MUTABLE / ARRAYS CAN BE CHANGED

 a[7] = 54 // ADDING A NEW VALUE TO THE ARRAY
 a[1] = 53 //CHANGING THE FIRST VALUE OF AN ARRAY
 console.log(a)
 console.log(typeof a) //ARRAYS ARE OBJECT. ARRAYS CAN HOLD MANY VALUES UNDER A SINGLE NAME.


 //DISPLAYING THE ARRAY ELEMENT USING FOR LOOP

 let b = [1,23,242,32]
 for(let i = 0; i<b.length;i++){
    console.log(b[i])
 }